merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.band_detail, name='band-detail'),
     path('bands/', views.band_list, name='band-list'),
     path('bands/<int:id>/',views.band_detail, name='band-detail'),
     path('bands/add/' , views.band_create, name='band-create'),
     path('contact-us/' ,views.contact,name='contact'),
     path('bands/delete/<int:id>', views.band_delete, name='band-delete'),
     path('bands/<int:id>/change/',views.band_update,name='band-update'),
     
   path('about-us/', views.about),
    
]

listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator



class Genre(models.TextChoices):
    HIP_HOP ='HH'
    SYNTH_POP ='SP'
    ALTERNATIVE_ROCK ='AR'



class Band(models.Model):
    
    # like_new =models.fields.BooleanField(default=False)   
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=5, choices=Genre.choices)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.IntegerField(validators= [MinValueValidator(1900),MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True,blank=True)
    
    
    def __str__(self):
        return f'{self.name}'
    
    
class Listing(models.Model):
    
     
    class ListingType(models.TextChoices):
         RECORDS ='R'
         CLOTHING ='C'
         POSTER ='P'
         NISC ='N'
         
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(null=True,blank=True, default=2004)
    type= models.fields.CharField(choices=ListingType.choices,max_length=5)
    band =models.ForeignKey("Band",null=True ,on_delete=models.SET_NULL)
    
    
    def __str__(self):
        return self.title
    

listings/forms.py
from django import forms
from listings.models import Band

class ConctactUsForm(forms.Form):
    name = forms.CharField(required = False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)
    
class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')

listings/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from listings.models import Band
from listings.forms import ConctactUsForm, BandForm
from django.core.mail import send_mail


def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('band-list')
    return render(request, 'listings/band_delete.html', {'band': band})

def band_update(request,id):
    band = Band.objects.get(id=id)
    if request.method =='POST':
        form = BandForm(request.POST, instance = band)
        if form.is_valid():
            form.save()
            return redirect('band-detail',band.id)
    else:
        
        form=BandForm(instance=band)
    
    return render(request,'listings/band_update.html',{'form' : form})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    
    return  render(request, 'listings/band_create.html', {'form': form})

    
    

def contact(request):
    
    if request.method =='POST':
        form = ConctactUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
                 
    else:
        form = ConctactUsForm()
    
    return redirect('email-sent')



def band_detail(request,id):
    band = Band.objects.get(id=id)
    return render(request,'listings/band_detail.html',{'band':band})
 

def band_list(request):
    bands = Band.objects.all()
    return render(request ,'listings/band_list.html',{'bands':bands})


def about(request):
    return HttpResponse('<h1> A Propos de nous </h1> <p>Nous Adherons merch!</p>')

listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}
{% block content %}
    <h1>Creer un nouveau groupe </h1>

    <form action="" method="post"  >
      {%  csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Envoyer">
    </form>
{% endblock %}

listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Supprimer le groupe </h1>
    <p>Etes-vous sur de vouloir supprimer le groupe : {{ band.name }} ? </p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
    </form>

{% endblock %}

listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}
{% block content %}
<h2>{{  band.name }}</h2>
<ul>
    <li>Genre : {{ band.get_genre_display }} </li>
    <li>Annee de formation : {{ band.year_formed}}</li>
    <li>Actif : {{band.active|yesno }}</li>
    {% if band.offivial_homepage %}
    <li><a href="{{band.official_homepage}}">{{band.official_homepage}}</a></li>  
    {% endif %}
    </ul>
    <p>{{ band.biography}}</p>
    <a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
    <a href="{% url 'band-list' %}">Retour a tous les groupes</a>

{% endblock %}

listings/templates/listings/band_list.html
 
 
 {% extends 'listings/base.html' %}
 
    {% block content %}

        <h1> Groupes</h1>
        <a href="{% url 'band-create' %}">Creer un nouveau groupe </a>
        <ul>
            {% for band in bands %}
              <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>-
            {% endfor %} 
        </ul>

    {% endblock %}
    

listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}
{% block content %}

    <h1>Mise a jour du groupe</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>


{% endblock %}

listings/templates/listings/base.html
{% load static %}
<html>
    <head>
<title>Merchex</title>
<link rel="stylesheet" href="{% static 'listings/style.css' %}" />
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupe Listings </a>
        </nav>

        {% block content %}{% endblock %}
    </body>
</html>

listings/templates/listings/contact.html
{% extends 'listings/base.html' %}
 
{% block content %}

    <h1>CONTACTEZ- NOUS </h1>

    <p>Nous sommes la pour vous aider. </p>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>

{% endblock %}